// Builds src/styles/tokens.generated.css from tokens/*.json — the single
// source of truth for every primitive (color, type scale, spacing, radius,
// dimension). Edit the JSON, run `bun run tokens:build` (or `bun run dev` /
// `build`, which do it for you), never hand-edit the generated file.
import StyleDictionary from 'style-dictionary';

const OUT_DIR = 'src/styles/';
const OUT_FILE = 'tokens.generated.css';

// clamp(min, mid, max) is stored pre-split (min/mid/max) rather than derived
// from a single interpolation formula: the original hand-tuned CSS used a
// different min↔max viewport slope per token, so the split value is the
// lossless source, not a shortcut.
const clamp = (v) => `clamp(${v.min}, ${v.mid}, ${v.max})`;
const dimensionValue = (v) => (typeof v === 'string' ? v : clamp(v));
const cssVar = (name, value) => `  --${name}: ${value};`;

StyleDictionary.registerFormat({
  name: 'css/mediaone-theme',
  format: ({ dictionary }) => {
    const byGroup = {};
    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path;
      (byGroup[group] ??= []).push({ name: rest.join('-'), value: token.$value ?? token.value });
    }

    const theme = ['@theme {'];
    for (const t of byGroup.font ?? []) theme.push(cssVar(`font-${t.name}`, t.value));
    for (const t of byGroup.breakpoint ?? []) theme.push(cssVar(`breakpoint-${t.name}`, t.value));
    for (const t of byGroup.color ?? []) theme.push(cssVar(`color-${t.name}`, t.value));
    for (const t of byGroup.text ?? []) {
      theme.push(cssVar(`text-${t.name}`, clamp(t.value)));
      theme.push(cssVar(`text-${t.name}--line-height`, t.value.lineHeight));
      theme.push(cssVar(`text-${t.name}--font-weight`, t.value.fontWeight));
    }
    for (const t of byGroup.radius ?? []) theme.push(cssVar(`radius-${t.name}`, dimensionValue(t.value)));
    for (const t of byGroup.width ?? []) theme.push(cssVar(`width-${t.name}`, t.value));
    for (const t of byGroup.container ?? []) theme.push(cssVar(`container-${t.name}`, t.value));
    theme.push('}');

    const spacing = [':root {'];
    for (const t of byGroup.spacing ?? []) spacing.push(cssVar(`spacing-${t.name}`, clamp(t.value)));
    spacing.push('}');

    return [
      '/* ============================================================================',
      '   AUTO-GENERATED by Style Dictionary — do not edit by hand.',
      '   Source: tokens/*.json — run `bun run tokens:build` after editing.',
      '   ============================================================================ */',
      theme.join('\n'),
      '',
      spacing.join('\n'),
      '',
    ].join('\n');
  },
});

const sd = new StyleDictionary({
  source: ['tokens/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: OUT_DIR,
      files: [{ destination: OUT_FILE, format: 'css/mediaone-theme' }],
    },
  },
});

await sd.buildPlatform('css');
